services:
  - type: web
    name: clothing-store
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn clothing_store.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: clothing-store.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://clothing-store.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: DATABASE_URL
        fromDatabase:
          name: clothing-store-db
          property: connectionString
  - type: postgresql
    name: clothing-store-db
